using DAL;
using BLL.Managers;
using BLL.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WEB.Pages
{
    public class CaretakerModel : PageModel
    {
        private readonly UserManager _userManager;
        private readonly AnimalManager _animalManager;

        public CaretakerModel()
        {
            _userManager = new UserManager(new UserDataAccess());
            _animalManager = new AnimalManager(new AnimalDataAccess());
        }

        public List<Employee> Employees { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public Role EmployeeRole { get; set; }
        [BindProperty]
        public AnimalNotes AnimalNotes { get; set; }
        //public string NewNote { get; set; }
        public int EmployeeId { get; set; }
        public List<BLL.Models.Task> AssignedTasks { get; set; }

        public void OnGet(int id)
        {
            var userIdClaim = HttpContext.User.FindFirst("empID");

            if (userIdClaim != null && int.TryParse(userIdClaim.Value, out int userId))
            {
                var employee = _userManager.GetEmployeeById(userId);

                if (employee != null)
                {
                    InitializeEmployeeProperties(employee);
                    LoadAssignedTasks(userId);
                }
                else
                {
                    // Handle the case where the employee isn't found
                }
            }
            else
            {
                // Handle the case where the user ID claim is missing or invalid
            }
        }

        private void InitializeEmployeeProperties(Employee employee)
        {
            Email = employee.Email;
            EmployeeRole = employee.Role;
            FirstName = employee.FirstName;
            // Set other properties here
        }

        private void LoadAssignedTasks(int employeeId)
        {
            // Assuming you have a method in your AnimalManager to get assigned tasks for an employee
            AssignedTasks = _animalManager.GetIncompleteTasks(employeeId);
        }

        public IActionResult OnPostNote()
        {
            int id = Convert.ToInt32(User.FindFirst("EmpID").Value);
            
            
            if (!string.IsNullOrEmpty(AnimalNotes.Note))
            {

                // Create a new task object with the necessary parameters
                AnimalNotes newNote = new AnimalNotes(
                    noteId: 0,  // Set to 0 if the ID is generated by the database
                    employeeId: id,
                    animalId: 1,  // Set the default value
                    note: AnimalNotes.Note,
                    createdAt: DateTime.Now
                        
                );

                // Assuming you have a method in your AnimalManager to add a note as a task
                _animalManager.AddNote(newNote);


                return RedirectToPage("/Caretaker");
            }
            

            // If none of the conditions are met, return a default result
            return Page();
        }
    }

    //public IActionResult OnPost()
    //{
    //    var userIdClaim = HttpContext.User.FindFirst("empID");
    //    if (userIdClaim != null && int.TryParse(userIdClaim.Value, out int employeeId))
    //    {
    //        if (!string.IsNullOrEmpty(NewNote))
    //        {
    //            // Fetch caretaker ID from claims
    //            var caretakerId = employeeId;
    //            var animalId = animalId;

    //            // Fetch animal ID (you need to define or retrieve animalId from somewhere)

    //            AnimalNotes newNote = new AnimalNotes
    //            {
    //                CaretakerId = caretakerId,
    //                AnimalId = animalId,
    //                Note = newNote,
    //                CreatedAt = DateTime.Now
    //            };

    //            _animalmanager.AnimalNotes.Add(newNote);
    //            _animalmanager.SaveChanges();
    //            return RedirectToPage("./CaretakerDashboard");
    //        }
    //    }

    // Handle cases where user ID or note is not valid or missing
    // You might want to add appropriate error handling or redirection here
    //    return Page();
    //}}

}